- fix in checking is netforking is up.
Changed files:
    mrt.init -> 1.6

diff --git a/mrt.init b/mrt.init
--- a/mrt.init
+++ b/mrt.init
@@ -20,7 +20,10 @@
 [ -f /etc/sysconfig/mrt ] && . /etc/sysconfig/mrt
 
 # Check that networking is up.
-[ "${NETWORKING}" == "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Mrt service can't be runed "
+	exit 1
+fi
 
 # Sanity checks.
 [ -f /etc/mrtd.conf ] || exit 0
